insert into SYS.WORKERS (WORKERID, WORKERNAME, WORKERPOSITION, NUMBEROFCLIENTS)
values (121743945, 'Joanna', 'Joanna', 1);

insert into SYS.WORKERS (WORKERID, WORKERNAME, WORKERPOSITION, NUMBEROFCLIENTS)
values (933797130, 'Johnnie', 'Johnnie', 9);

insert into SYS.WORKERS (WORKERID, WORKERNAME, WORKERPOSITION, NUMBEROFCLIENTS)
values (209467651, 'Petula', 'Petula', 8);

insert into SYS.WORKERS (WORKERID, WORKERNAME, WORKERPOSITION, NUMBEROFCLIENTS)
values (961975546, 'Robin', 'Robin', 8);

insert into SYS.WORKERS (WORKERID, WORKERNAME, WORKERPOSITION, NUMBEROFCLIENTS)
values (498745274, 'Alan', 'Alan', 2);

insert into SYS.WORKERS (WORKERID, WORKERNAME, WORKERPOSITION, NUMBEROFCLIENTS)
values (992107902, 'Elvis', 'Elvis', 7);

insert into SYS.WORKERS (WORKERID, WORKERNAME, WORKERPOSITION, NUMBEROFCLIENTS)
values (129776178, 'Maxine', 'Maxine', 7);

insert into SYS.WORKERS (WORKERID, WORKERNAME, WORKERPOSITION, NUMBEROFCLIENTS)
values (980654890, 'Holly', 'Holly', 10);

insert into SYS.WORKERS (WORKERID, WORKERNAME, WORKERPOSITION, NUMBEROFCLIENTS)
values (368261673, 'Wang', 'Wang', 6);

insert into SYS.WORKERS (WORKERID, WORKERNAME, WORKERPOSITION, NUMBEROFCLIENTS)
values (257733119, 'Clive', 'Clive', 8);

insert into SYS.WORKERS (WORKERID, WORKERNAME, WORKERPOSITION, NUMBEROFCLIENTS)
values (851028218, 'Chaka', 'Chaka', 3);

insert into SYS.WORKERS (WORKERID, WORKERNAME, WORKERPOSITION, NUMBEROFCLIENTS)
values (686070688, 'Willem', 'Willem', 5);

commit;

